spring:
  datasource:
    url: "jdbc:h2:file:/opt/photo-gallery.h2;MODE=LEGACY;DB_CLOSE_ON_EXIT=TRUE"

lib.location: "/media/hotaro/Data/Photos,/media/hotaro/Data/GooglePhotos-All"
lib.previewLocation: "/opt/photo-gallery-previews"