CREATE TABLE MEDIA_ENTITY
(
    ID            LONG          NOT NULL PRIMARY KEY AUTO_INCREMENT,
    FILE_NAME     VARCHAR(255)  NOT NULL,
    FULL_PATH     VARCHAR(2048) NOT NULL,
    PARSED_DATE   LONG          NOT NULL,
    OVERRIDE_DATE LONG,
    IS_BROKEN     BOOLEAN       NOT NULL,
    IS_FINAL      BOOLEAN       NOT NULL
);

CREATE INDEX MEDIA_ENTITY_FILE_NAME_INDEX ON MEDIA_ENTITY (FILE_NAME);
CREATE INDEX MEDIA_ENTITY_FULL_PATH_INDEX ON MEDIA_ENTITY (FULL_PATH);